n1 = int(input())
n2 = int(input())
n3 = int(input())
# print(round((n1 + n2 + n3)// 2))
res1 = (n1 / 2)
print(res1)
print(round(res1,2))
res2 = round(n2 / 2)
print(res2)
print(round(res2,2))
res3 = round(n3 / 2)
print(res3)
print(round(res3,2))
sum = res1 + res2 + res3
print(sum)