print("Доброе время суток!")
f_name = input("Укажите вашу фамилию: ")
name = input("Укажитте ваше имя: ")
city = input("Укажите город в котором вы живете: ")
print('вас зовут ' + f_name.title() + name.title()  + ', вы живёте в ' + city.title())